version: '3'

services:

  nginx:
    build: ./nginx
    ports:
     - "80:80"
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web

  web:
    build: ./web_app
    env_file: ./.env
    command: /code/run.sh
    volumes:
        - ./web_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: