# Generated by Django 4.0.3 on 2022-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('url', models.URLField(unique=True)),
                ('geo', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('notes', models.TextField(default='')),
                ('cat_seen', models.ManyToManyField(to='news.category')),
            ],
        ),
        migrations.CreateModel(
            name='SERPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('date_check', models.DateTimeField(auto_now_add=True)),
                ('website', models.ManyToManyField(to='news.website')),
            ],
        ),
    ]
