# Generated by Django 4.0.3 on 2022-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_website_cat_seen_remove_website_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
