# Generated by Django 4.0.3 on 2022-04-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_querycheck_websitecheckscore_delete_serpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='querycheck',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.website'),
        ),
        migrations.AlterField(
            model_name='querycheck',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.query'),
        ),
    ]
