# Generated by Django 4.0.3 on 2022-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_query_alter_querycheck_website_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='name',
        ),
    ]
