# Generated by Django 4.0.3 on 2022-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_query_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='location',
            field=models.CharField(choices=[('USA', 'United States'), ('United Kingdom, London', 'London,England,United Kingdom'), ('France, Paris', 'Paris,Ile-de-France,France')], default='United States', max_length=255),
        ),
    ]
