# Generated by Django 4.0.3 on 2022-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_query_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'queries'},
        ),
        migrations.RenameField(
            model_name='query',
            old_name='name',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='query',
            name='location',
            field=models.CharField(choices=[('United States', 'USA'), ('New York,New York,United States', 'USA, New York'), ('Los Angeles,California,United States', 'USA, Los Angeles (CA)'), ('London,England,United Kingdom', 'UK, London'), ('Paris,Ile-de-France,France', 'France, Paris')], default='United States', max_length=255),
        ),
    ]
